version: '3.5'

services:
  backend:
    container_name: user_api_backend_container
    image: 'user_api_backend_iso'
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8080"
    environment:
      - SPRING_SERVER_PORT=8080
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user_db

  db:
    container_name: user_api_db_container
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_db
    image: postgres:16.1-alpine